version: '3.8'

services:
  server:
    build: 
      context: ./server
    command: >
      bash -c "python manage.py migrate
      && python manage.py generatequestions 
      && daphne -b 0.0.0.0 -p 8000 core.asgi:application"
    ports:
      - 8000:8000
    expose:
      - 8000
    environment:
      - SECRET_KEY=django-insecure-566c-hrff#zl8#69@-wbr+y@i-7g92w&r@f#tg7cfkag4nm=@*
      - DB_NAME=postgres
      - DB_USER=postgres 
      - DB_PASSWORD=postgres 
      - DB_HOST=db
      - DB_PORT=5432 
      - CLIENT_HOST=http://localhost:3000
      - REDIS_HOST=redis://broker:6379/0
    depends_on:
      - db
      - broker

  db:
    image: postgres
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  broker:
    image: redis
    ports:
      - 6379:6379
    expose:
      - 6379  

  client:
    build: 
      context : ./client
    volumes:
      - react_build:/react/build
    depends_on:
      - server

  nginx:
    image: nginx
    ports:
      - 80:8080
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - react_build:/var/www/react
    depends_on:
      - server
      - client

volumes:
  pgdata:     
  react_build: 